# Generated by Django 4.1.1 on 2022-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_movie_actor_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Epics', 'Epics'), ('Serial', 'Serial'), ('Documentary', 'Documentary'), ('Dedective', 'Dedective'), ('Fantastic', 'Fantastic'), ('Scientific', 'Scientific'), ('Artistic', 'Artistic'), ('Historical', 'Historical')], max_length=150),
        ),
    ]
